services:
  traefik-testapp-2:
    image: nginx:mainline-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      # HTTPS router
      - "traefik.http.routers.traefik-testapp-2.entrypoints=websecure"
      - "traefik.http.routers.traefik-testapp-2.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.traefik-testapp-2.tls=true"

    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jedi-proxy

networks:
  jedi-proxy:
    external: true
